tags:
- name: "operation"
  description: "Operations that can be performed on one or all videos"
paths:
  /operation/bufferStatus:
    get:
      tags:
      - "operation"
      summary: "Reads the buffer status of one or all videos"
      produces:
      - "application/json"
      parameters:
      - name: "oveSectionId"
        in: "query"
        type: "integer"
        format: "int32"
        description: "Section ID"
        required: false
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                enum: ["complete", "buffering"]
  /operation/pause:
    get:
      tags:
      - "operation"
      summary: "Pauses playback on one or all videos"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
  /operation/play:
    get:
      tags:
      - "operation"
      summary: "Plays one or all videos"
      produces:
      - "application/json"
      parameters:
      - name: "loop"
        in: "query"
        type: "string"
        enum: ["true", "false"]
        description: "Loop playback or not"
        required: false
      - name: "oveSectionId"
        in: "query"
        type: "integer"
        format: "int32"
        description: "Section ID"
        required: false
      responses:
        200:
          description: "successful operation"
  /operation/seekTo:
    get:
      tags:
      - "operation"
      summary: "Seeks to a specific time one or all videos"
      produces:
      - "application/json"
      parameters:
      - name: "time"
        in: "query"
        type: "number"
        format: "float"
        description: "Time in seconds from start of video"
        required: true
      - name: "oveSectionId"
        in: "query"
        type: "integer"
        format: "int32"
        description: "Section ID"
        required: false
      responses:
        200:
          description: "successful operation"
  /operation/stop:
    get:
      tags:
      - "operation"
      summary: "Stops playback one or all videos and resets time to the start"
      produces:
      - "application/json"
      parameters:
      - name: "oveSectionId"
        in: "query"
        type: "integer"
        format: "int32"
        description: "Section ID"
        required: false
      responses:
        200:
          description: "successful operation"
externalDocs:
  description: "Find out more about OVE"
  url: "https://dsi.gitbook.io/ove"
